USE db_autogenerated;

#Para poder hacer DELETE y UPDATE
SET SQL_SAFE_UPDATES = 0;

#1
select postalZip as codigoPostal, region as provincia, country as pais from mytable;

#2
SELECT * FROM mytable where phone like '%(811)%';

#3
select * from mytable where country = 'spain' or country = 'italy';

#4
SELECT COUNT(*) as count FROM mytable;

#5
select region, country, postalZip from 	mytable where 	country in (
	select country from mytable where country = 'Germany' or country = 'Turkey');

#6
select MAX(id), MIN(id) from mytable;

#7
select count(country), country from mytable group by country;

#8
select * from mytable order by postalZip limit 10;

#9
select * from mytable where country = 'Singapore';
delete from mytable where country = 'Singapore';
select * from mytable where country = 'Singapore';

#10
update mytable set country = 'Espanya' where country = 'Spain';
select * from mytable where country = 'Espanya';


