USE db_autogenerated;

#1
select postalZip as codigoPostal, region as provincia, country as pais from mytable;

#2
SELECT * FROM mytable where phone like '%(811)%';

#3
select * from mytable where country = 'spain' or country = 'italy';

#4
SELECT COUNT(*) as count FROM mytable;

#5
select region, country, postalZip from 	mytable where 	country in (
	select country from mytable where country = 'Germany' or country = 'Turkey');

#6

